default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
        exclude: research/|tools/
      - id: check-case-conflict
        exclude: research/|tools/
      - id: check-merge-conflict
        exclude: research/|tools/
      - id: end-of-file-fixer
        exclude: manual_moderation_service/src/db/migrations/|research/|tools/|moderation_frontend/
        exclude_types:
          [svg, css, html, less, javascript, json, coffee, map, markdown, pem]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: research/

  - repo: local
    hooks:
      - id: ruff_format
        name: ruff format
        entry: .venv/bin/ruff
        language: python
        types: [python]
        args: [format]
        exclude: research/|moderation_frontend/|tools/
        require_serial: false
        additional_dependencies: []

      - id: ruff_lint
        name: ruff lint
        entry: .venv/bin/ruff
        language: python
        types: [python]
        args: [check]
        exclude: manual_moderation_service/src/db/migrations/|research/|moderation_frontend/|tools/
        require_serial: false
        additional_dependencies: []

      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: python
        types: [python]
        args: [--config-file, pyproject.toml]
        exclude: manual_moderation_service/src/db/migrations/|research/|moderation_frontend/|tools/
        require_serial: false
        additional_dependencies: []
