version: '3.4'

x-mongo-defaults: &mongo-defaults
  image: mongo
  restart: always
  expose:
    - "27017"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
    interval: 5s
    timeout: 5s
    retries: 3
    start_period: 5s

x-mongos-defaults: &mongos-defaults
  image: mongo
  restart: always
  command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
  expose:
    - "27017"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  depends_on:
    - mongocfg1
    - mongocfg2

services:
  nginx:
    image: nginx:latest
    container_name: ugc-nginx
    restart: always
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/sites:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - ugc-api
    networks:
      - graduate_work_network

  ugc-api:
    build:
      context: .
      dockerfile: ./ugc_api/Dockerfile
    container_name: ugc-api
    image: ugc-api-image
    restart: always
    env_file:
      - ./.env
    ports:
      - "8010:8000"
    volumes:
      - ./ugc_api/src:/app/src
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - graduate_work_network

  ugc-api-test:
    build:
      context: .
      dockerfile: ./ugc_api/Dockerfile.test
    container_name: ugc-api-test
    image: ugc-api-test-image
    env_file:
      - ./.env
    environment:
      - SENTRY_DSN=
    volumes:
      - ./ugc_api/src:/app/src 
    networks:
      - graduate_work_network

networks:
  graduate_work_network:
    name: graduate_work_network
    external: true
