version: '3.9'

volumes:
  loki_data:
  grafana_data:

networks:
  graduate_work_network:
    name: graduate_work_network
    external: true

services:
  promtail:
    image: grafana/promtail:2.6.0
    user: root
    container_name: promtail
    hostname: promtail
    ports:
      - 9080:9080
    restart: always
    volumes:
      - ./logs/promtail/promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - /var/lib:/var/lib:ro
      - /run/log/journal/:/run/log/journal/
      - /opt/logs:/opt/logs:ro
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - graduate_work_network
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: json-file
      options:
        max-size: "10m"

  loki:
    image: grafana/loki:2.6.0
    user: root
    container_name: loki
    hostname: loki
    ports:
      - 3100:3100
    restart: always
    volumes:
      - loki_data:/tmp/loki
      - ./logs/loki/loki.yaml:/etc/loki/local-config.yaml
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    networks:
      - graduate_work_network
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: json-file
      options:
        max-size: "10m"
  
  grafana:
    image: grafana/grafana:9.5.2
    user: root
    depends_on:
      - loki
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_DATABASE_TYPE=${GF_DATABASE_TYPE}
      - GF_DATABASE_PATH=${GF_DATABASE_PATH}
      - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=${GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH}
      - GF_LOG_MODE=${GF_LOG_MODE}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE}
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - graduate_work_network
    labels:
      org.label-schema.group: "monitoring"
    volumes:
      - ./logs/grafana/custom.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
      - ./logs/grafana/provisioning:/etc/grafana/provisioning
      - ./logs/grafana/dashboards:/var/lib/grafana/dashboards
    logging:
      driver: json-file
      options:
        max-size: "10m"
