FROM node:20-alpine

# Установка дополнительных пакетов для решения возможных проблем
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Копируем файлы зависимостей
COPY frontend/package.json frontend/package-lock.json* ./

# Устанавливаем зависимости с расширенными параметрами
RUN npm install --verbose --force

# Копируем исходный код
COPY frontend/ ./

# Открываем порт для Next.js в режиме разработки
# Nginx будет проксировать запросы на этот порт
EXPOSE 3000

# Удаляем переменную окружения для базового пути, так как у нас несколько маршрутов
# ENV NEXT_PUBLIC_BASE_PATH="/moderation"

# Настройка для доступа извне контейнера
ENV HOSTNAME=0.0.0.0

# Запускаем режим разработки
CMD ["npm", "run", "dev"] 
