# Generated by Django 5.1.6 on 2025-03-06 18:46

# thirdparty
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.UUIDField(verbose_name="ID пользователя")),
                ("movie_id", models.UUIDField(verbose_name="ID фильма")),
                ("review_id", models.UUIDField(verbose_name="ID рецензии")),
                ("review_text", models.TextField(verbose_name="Текст рецензии")),
                ("auto_moderation_result", models.TextField(null=True, verbose_name="Результат автомодерации")),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        verbose_name="Статус модерации",
                    ),
                ),
                ("rejection_reason", models.TextField(null=True, verbose_name="Причина отказа")),
                ("moderator_id", models.UUIDField(null=True, verbose_name="ID модератора")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("moderation_at", models.DateTimeField(auto_now=True, verbose_name="Дата модерации")),
            ],
            options={
                "verbose_name": "Рецензия",
                "verbose_name_plural": "Рецензии",
            },
        ),
    ]
