"""001_create_review

Revision ID: d40cc348551a
Revises:
Create Date: 2025-03-06 23:38:14.808855

"""

# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d40cc348551a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("movie_id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("review_title", sa.Text(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=False),
        sa.Column("auto_moderation_result", sa.Text(), nullable=True),
        sa.Column(
            "moderation_status", sa.Enum("PENDING", "APPROVED", "REJECTED", name="moderationstatus"), nullable=False
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("moderator_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("moderation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        comment="Reviews",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
